# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 15:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Формат телефонного номера: '9163171489'.", regex='^\\d{10}$')])),
                ('claim_text', models.TextField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('claim_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
