# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20161019_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='email',
        ),
        migrations.AddField(
            model_name='claim',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
